# .github/workflows/3.0-standalone-io-secret.yaml
name: 3.1 standalone io secret env

# on: [workflow_dispatch]

on:
  workflow_dispatch:
    inputs:
      my-input:
          description: 'Branch/tag/hash to build'
          required: true
          default: 'default input value'

# jobs:
#   job1:
#     uses: niftyworx01/02-gha-reusable/.github/workflows/my-reusable-workflow.yaml@master
#     with:
#       my-input:  ${{ inputs.my-input }}

jobs:
  simple-call:
    runs-on: ubuntu-latest

    steps:
      - name: Set env variables
        run: echo "my_input_env=${{inputs.my-input}}" >> $GITHUB_ENV

      - name: Run tests
        run: |
          # echo "test output"
          # echo "Output calling repo's secret ${{ secrets.NIF360_SECRET1 }}"
          if [[ "${{ secrets.NIF360_SECRET1 }}" == "${{ inputs.my-input }}" ]]; then
            echo "Secrets and input is equal. Input is: ${{ inputs.my-input }}"
            echo "Secrets and input is equal. Input is: ${{ env.my_input_env }}"
          else
            echo "Secrets and input is NOT equal. Input is: ${{ inputs.my-input }}"
            echo "Secrets and input is NOT equal. Input is: ${{ env.my_input_env }}-test"
          fi