name: Hello World
on: [push]
jobs:
  Hello-World-Job:
    runs-on:
      - codebuild-org-level-3-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - run: echo "Hello 02-nif2-org-pub-calling-repo1!"
