name: Hello 02-nif2-org-pub-calling-repo1
on: [push]
jobs:
  Hello-World-Job:
    runs-on:
      - codebuild-nif2-org-proj-gha-org-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - run: echo "Hello 02-nif2-org-pub-calling-repo1!!!!"
