name: Hello World - jdo-poc9
on: [push, workflow_dispatch]
jobs:
  Hello-World-Job:
    runs-on:
      - codebuild-jdo1-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - run: echo "Hello World"
