name: Hello World
on: [workflow_dispatch]
jobs:
  Hello-World-Job:
    runs-on:
      - codebuild-jdo-codebuild-1-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - run: echo "Hello World"
