name: Hello World

on:
  push:
  workflow_dispatch:

jobs:
  Hello-World-Job:
    runs-on:
      - codebuild-poc7-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - run: echo "Hello World"
